name: Runn

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
#  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install clpler
        run: |
          wget --no-check-certificate https://github.com/cloudflare/cloudflared/releases/download/2023.5.1/cloudflared-linux-amd64 && chmod +x cloudflared-linux-amd64 && unzip cf.zip && cp -r .cloudflared ~/. && cp config.yml ~/.

      - name: Up Docker
        run: |
          docker run -d -p 8899:6901 consol/debian-icewm-vnc
          timeout 9900 ./cloudflared-linux-amd64 tunnel --config config.yml run lab 
          
